In [1]:
from keras.datasets import imdb


(X_train, Y_train), (X_test, Y_test) = imdb.load_data()

/usr/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)
Using TensorFlow backend.


In [2]:
word_index = imdb.get_word_index()

In [5]:
index_to_word = {val:key for (key, val) in word_index.items()}

In [6]:
rev = ' '.join(index_to_word.get(val-3 , 'UNK') for val in X_train[1])
print(rev)

print(Y_train[1])


UNK big hair big boobs bad music and a giant safety pin these are the words to best describe this terrible movie i love cheesy horror movies and i've seen hundreds but this had got to be on of the worst ever made the plot is paper thin and ridiculous the acting is an abomination the script is completely laughable the best is the end showdown with the cop and how he worked out who the killer is it's just so damn terribly written the clothes are sickening and funny in equal measures the hair is big lots of boobs bounce men wear those cut tee shirts that show off their stomachs sickening that men actually wore them and the music is just synthesiser trash that plays over and over again in almost every scene there is trashy music boobs and paramedics taking away bodies and the gym still doesn't close for bereavement all joking aside this is a truly bad film whose only charm is to look back on the disaster that was the 80's and have a good old laugh at how bad everything was back then
0


In [8]:
import numpy as np
X = np.concatenate((X_train, X_test), axis=0)
Y = np.concatenate((Y_train, Y_test), axis=0)
X.shape

(50000,)

In [9]:
unique_words = np.unique(np.hstack(X_train))

In [10]:
print(len(unique_words))
# print(X.shape)

88585


In [11]:
from keras.preprocessing import sequence
X_train = sequence.pad_sequences(X_train, maxlen=500)
X_test = sequence.pad_sequences(X_test, maxlen=500)

In [12]:
from keras.layers import Dense, Flatten
from keras.layers.embeddings import Embedding
from keras.models import Sequential

seed = 7
np.random.seed(seed)


In [129]:
model = Sequential()
model.add(Embedding(88587, 32, input_length=500))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
# model.add(Dense(250, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 500, 32)           2834784   
_________________________________________________________________
flatten_7 (Flatten)          (None, 16000)             0         
_________________________________________________________________
dense_13 (Dense)             (None, 64)                1024064   
_________________________________________________________________
dense_14 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 65        
Total params: 3,863,073
Trainable params: 3,863,073
Non-trainable params: 0
_________________________________________________________________
None


In [170]:
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=5)

Train on 25000 samples, validate on 25000 samples
Epoch 1/5
25000/25000 [==============================] - 220s 9ms/step - loss: 0.3650 - acc: 0.8270 - val_loss: 0.2833 - val_acc: 0.8849
Epoch 2/5
25000/25000 [==============================] - 216s 9ms/step - loss: 0.1430 - acc: 0.9489 - val_loss: 0.3033 - val_acc: 0.8789
Epoch 3/5
25000/25000 [==============================] - 218s 9ms/step - loss: 0.0674 - acc: 0.9783 - val_loss: 0.4112 - val_acc: 0.8710
Epoch 4/5
25000/25000 [==============================] - 218s 9ms/step - loss: 0.0335 - acc: 0.9899 - val_loss: 0.5420 - val_acc: 0.8498
Epoch 5/5
25000/25000 [==============================] - 219s 9ms/step - loss: 0.0275 - acc: 0.9910 - val_loss: 0.5875 - val_acc: 0.8595


In [171]:
scores = model.evaluate(X_test, Y_test, verbose=2)
print("Accuracy: %.2f%%" % (scores[1]*100))
print(scores)

Accuracy: 85.95%
[0.5875436723542213, 0.85948]


In [172]:
result = model.predict_classes(X_test)

In [173]:
print(Y_test[21:58])
print(np.hstack(result[21:58]))

[1 1 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 1]
[1 0 1 1 1 0 1 0 0 1 1 1 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1]


In [125]:
# text = "big hair big boobs bad music and a giant safety pin these are the words to best describe this terrible movie i love cheesy horror movies and i've seen hundreds but this had got to be on of the worst ever made the plot is paper thin and ridiculous the acting is an abomination the script is completely laughable the best is the end showdown with the cop and how he worked out who the killer is it's just so damn terribly written the clothes are sickening and funny in equal measures the hair is big lots of boobs bounce men wear those cut tee shirts that show off their stomachs sickening that men actually wore them and the music is just synthesiser trash that plays over and over again in almost every scene there is trashy music boobs and paramedics taking away bodies and the gym still doesn't close for bereavement all joking aside this is a truly bad film whose only charm is to look back on the disaster that was the 80's and have a good old laugh at how bad everything was back then"
text = "bad management"

text_split = text.split()

In [207]:
from nltk.corpus import stopwords
import re
text = "it was average value but didn't up to the mark"
text_split = text.lower().split()

text_to_index = [word_index[val]+3 if val in word_index else 0 for val in text_split ]
text_to_index = sequence.pad_sequences([text_to_index], 500)
res = model.predict_classes([text_to_index])
res

array([[0]], dtype=int32)

In [169]:
from keras.layers import Dropout, Conv1D, MaxPooling1D, LSTM, Activation
model = Sequential()

# Embedding layer
model.add(Embedding(88587, 
                    50, 
                    input_length=500))
model.add(Dropout(0.25))

# Convolutional layer
model.add(Conv1D(64,
                5,
                padding='valid',
                activation='relu',
                strides=1))
model.add(MaxPooling1D(pool_size=4))

# LSTM layer
model.add(LSTM(70))

# Squash
model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_12 (Embedding)     (None, 500, 50)           4429350   
_________________________________________________________________
dropout_3 (Dropout)          (None, 500, 50)           0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 496, 64)           16064     
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 124, 64)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 70)                37800     
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 71        
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total para